services:
  # Backend
  - type: web
    name: aaucagym-backend
    env: docker
    repo: https://github.com/Tranquilino1/AAUCAGYM
    rootDir: gym-backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://YOUR_DB_HOST:3306/gimnasio_db
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: YOUR_PASSWORD
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  # Frontend
  - type: web
    name: aaucagym-frontend
    env: static
    repo: https://github.com/Tranquilino1/AAUCAGYM
    rootDir: gym-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist/gym-frontend
