# Definición de la Base de Datos MySQL
databases:
  - name: aaucagym-db
    engine: mysql
    plan: free

services:
  # Backend
  - type: web
    name: aaucagym-backend
    env: docker
    repo: https://github.com/Tranquilino1/AAUCAGYM
    rootDir: gym-backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: aaucagym-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: aaucagym-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: aaucagym-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  # Frontend
  - type: web
    name: aaucagym-frontend
    env: static
    repo: https://github.com/Tranquilino1/AAUCAGYM
    rootDir: gym-frontend
    buildCommand: npm install && npm run build
    [cite_start]staticPublishPath: dist/gym-frontend [cite: 1]