# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gimnasio_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security
# Disabling basic auth for now to facilitate initial development, will configure properly later
# spring.security.user.name=admin
# spring.security.user.password=admin
